<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
    	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<?= $this->headTitle('Sikha')->setSeparator(' :: ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('keywords', '')
	        ->appendName('description', '')
	        ->appendName('language', 'English')
	        ->appendName('author', 'Khaleb Great')
        ?>

        <?= $this->headLink(['rel' => 'stylesheet', 'href' => 'https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700']) ?>

        <?php
            echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . 'assets/media/logos/favicon.ico'])
            ->offsetSetStylesheet(80, $this->basePath('assets/css/themes/layout/aside/dark.css'), '')
            ->offsetSetStylesheet(70, $this->basePath('assets/css/themes/layout/brand/dark.css'), '')
            ->offsetSetStylesheet(60, $this->basePath('assets/css/themes/layout/header/menu/light.css'), '')
            ->offsetSetStylesheet(50, $this->basePath('assets/css/themes/layout/header/base/light.css'), '')
            ->offsetSetStylesheet(40, $this->basePath('assets/css/style.bundle.css'), '')
            ->offsetSetStylesheet(30, $this->basePath('assets/plugins/custom/prismjs/prismjs.bundle.css'), '')
            ->offsetSetStylesheet(20, $this->basePath('assets/plugins/global/plugins.bundle.css'), '');
        ?>

	</head>
    <body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled subheader-fixed aside-enabled aside-fixed aside-minimize-hoverable page-loading">

		<?= $this->content ?>
		
		<script>var HOST_URL = "";</script>
		<script>
			var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1400 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#3699FF", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#E4E6EF", "dark": "#181C32" }, "light": { "white": "#ffffff", "primary": "#E1F0FF", "secondary": "#EBEDF3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#3F4254", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#EBEDF3", "gray-300": "#E4E6EF", "gray-400": "#D1D3E0", "gray-500": "#B5B5C3", "gray-600": "#7E8299", "gray-700": "#5E6278", "gray-800": "#3F4254", "gray-900": "#181C32" } }, "font-family": "Poppins" };
		</script>

		<?= $this->headScript()
			->offsetSetFile(30, $this->basePath('assets/js/scripts.bundle.js'))
			->offsetSetFile(20, $this->basePath('assets/plugins/custom/prismjs/prismjs.bundle.js'))
			->offsetSetFile(10, $this->basePath('assets/plugins/global/plugins.bundle.js'));
		?>
		<?= $this->inlineScript() ?>
    </body>
</html>
