<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
    	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<?= $this->headTitle('Sikha')->setSeparator(' :: ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1, shrink-to-fit=no')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('keywords', '')
	        ->appendName('description', '')
	        ->appendName('language', 'English')
	        ->appendName('author', 'Khaleb Great')
        ?>
		<?php
            echo $this->headLink(['rel' => 'icon', 'type' => 'image/png', 'href' => $this->basePath() . 'assets/img/favicon.png'])
		?>

        <?php
            echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . 'assets/media/logos/favicon.ico'])
            ->offsetSetStylesheet(100, $this->basePath('blog_assets/css/responsive.css'), '')
            ->offsetSetStylesheet(90, $this->basePath('blog_assets/css/style.css'), '')
            ->offsetSetStylesheet(80, $this->basePath('blog_assets/css/nice-select.min.css'), '')
            ->offsetSetStylesheet(70, $this->basePath('blog_assets/css/magnific-popup.min.css'), '')
            ->offsetSetStylesheet(60, $this->basePath('blog_assets/css/owl.theme.default.min.css'), '')
            ->offsetSetStylesheet(50, $this->basePath('blog_assets/css/owl.carousel.min.css'), '')
            ->offsetSetStylesheet(40, $this->basePath('blog_assets/css/boxicons.min.css'), '')
            ->offsetSetStylesheet(30, $this->basePath('blog_assets/css/meanmenu.css'), '')
            ->offsetSetStylesheet(20, $this->basePath('blog_assets/css/animate.min.css'), '')
            ->offsetSetStylesheet(10, $this->basePath('blog_assets/css/bootstrap.min.css'), '');
        ?>
	</head>
	<body>
		<div class="preloader">
			<div class="loader">
				<div class="wrapper">
					<div class="circle circle-1"></div>
					<div class="circle circle-1a"></div>
					<div class="circle circle-2"></div>
					<div class="circle circle-3"></div>
				</div>
				<span>Loading...</span>
			</div>
		</div>

		<div class="top-header-area">
			<div class="container">
				<div class="row align-items-center">
					<div class="col-lg-6">
						<ul class="top-header-social">
							<li>
								<a href="#" class="facebook" target="_blank">
									<i class="bx bxl-facebook"></i>
								</a>
							</li>
							<li>
								<a href="#" class="pinterest" target="_blank">
									<i class="bx bxl-instagram"></i>
								</a>
							</li>
							<li>
								<a href="#" class="pinterest" target="_blank">
									<i class="bx bxl-linkedin"></i>
								</a>
							</li>
							<li>
								<a href="#" class="twitter" target="_blank">
									<i class="bx bxl-twitter"></i>
								</a>
							</li>
							<li>
								<a href="#" class="linkedin" target="_blank">
									<i class="bx bxl-youtube"></i>
								</a>
							</li>
						</ul>
					</div>
					<div class="col-lg-6">
						<ul class="top-header-others">
							<li>
								<div class="languages-list">
									<select>
										<option value="1">English</option>
										<option value="2">العربيّة</option>
										<option value="3">Deutsch</option>
										<option value="3">Português</option>
										<option value="3">简体中文</option>
									</select>
								</div>
							</li>
							<li>
								<i class="bx bx-user"></i>
								<a href="login.html">Login</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
		
	<div class="navbar-area">
      <div class="main-responsive-nav">
        <div class="container">
          <div class="main-responsive-menu">
            <div class="logo">
              <a href="index-2.html">
				  <img src="blog_assets/imgs/logo-1.png" alt="image" />
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="main-navbar">
        <div class="container">
          <nav class="navbar navbar-expand-md navbar-light">
            <a class="navbar-brand" href="index-2.html">
				<img src="blog_assets/imgs/logo-1.png" alt="image" />
            </a>
            <div
              class="collapse navbar-collapse mean-menu"
              id="navbarSupportedContent"
            >
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a href="#" class="nav-link active"> Home </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link"> About </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link"> TOC </a>
                </li>
                <li class="nav-item">
                  <a href="#" class="nav-link"> Privacy Policy </a>
                </li>
              </ul>
              <div class="others-options d-flex align-items-center">
                <div class="option-item">
                  <form class="search-box">
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Search for.."
                    />
                    <button type="submit"><i class="bx bx-search"></i></button>
                  </form>
                </div>
              </div>
            </div>
          </nav>
        </div>
      </div>
      <div class="others-option-for-responsive">
        <div class="container">
          <div class="dot-menu">
            <div class="inner">
              <div class="circle circle-one"></div>
              <div class="circle circle-two"></div>
              <div class="circle circle-three"></div>
            </div>
          </div>
          <div class="container">
            <div class="option-inner">
              <div class="others-options d-flex align-items-center">
                <div class="option-item">
                  <form class="search-box">
                    <input
                      type="text"
                      class="form-control"
                      placeholder="Search for.."
                    />
                    <button type="submit"><i class="bx bx-search"></i></button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

		<?= $this->content ?>
		
	<section class="footer-area pt-100 pb-70">
      <div class="container">
        <div class="row">
          <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget">
              <a href="#">
				  <img src="blog_assets/imgs/logo-3.png" alt="image" />
              </a>
              <p>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </p>
              <ul class="social">
                <li>
                  <a href="#" class="facebook" target="_blank">
                    <i class="bx bxl-facebook"></i>
                  </a>
                </li>
                <li>
                  <a href="#" class="twitter" target="_blank">
                    <i class="bx bxl-instagram"></i>
                  </a>
                </li>
                <li>
                  <a href="#" class="linkedin" target="_blank">
                    <i class="bx bxl-twitter"></i>
                  </a>
                </li>
                <li>
                  <a href="#" class="linkedin" target="_blank">
                    <i class="bx bxl-youtube"></i>
                  </a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget">
              <h2>Recent post</h2>
              <div class="post-content">
                <div class="row align-items-center">
                  <div class="col-md-4">
                    <div class="post-image">
                      <a href="#">
						  <img src="blog_assets/imgs/recent-post/recent-post-1.jpg" alt="image" />
                      </a>
                    </div>
                  </div>
                  <div class="col-md-8">
                    <h4>
                      <a href="#">The match of the volleyball full of excitement</a>
                    </h4>
                    <span>28 Sep 2021</span>
                  </div>
                </div>
              </div>
              <div class="post-content">
                <div class="row align-items-center">
                  <div class="col-md-4">
                    <div class="post-image">
                      <a href="#">
						  <img src="blog_assets/imgs/recent-post/recent-post-2.jpg" alt="image" />
                      </a>
                    </div>
                  </div>
                  <div class="col-md-8">
                    <h4>
                      <a href="#"
                        >The match of the volleyball full of excitement</a
                      >
                    </h4>
                    <span>28 Sep 2021</span>
                  </div>
                </div>
              </div>
              <div class="post-content">
                <div class="row align-items-center">
                  <div class="col-md-4">
                    <div class="post-image">
                      <a href="#">
						  <img src="blog_assets/imgs/recent-post/recent-post-3.jpg" alt="image" />
                      </a>
                    </div>
                  </div>
                  <div class="col-md-8">
                    <h4>
                      <a href="#"
                        >The match of the volleyball full of excitement</a
                      >
                    </h4>
                    <span>28 Sep 2021</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget">
              <h2>Useful links</h2>
              <ul class="useful-links-list">
                <li>
                  <a href="#">Contact us</a>
                </li>
                <li>
                  <a href="#">News</a>
                </li>
                <li>
                  <a href="#">Privacy & policy</a>
                </li>
                <li>
                  <a href="#">Terms & conditions</a>
                </li>
                <li>
                  <a href="#">Affilate ads</a>
                </li>
                <li>
                  <a href="#">Business</a>
                </li>
                <li>
                  <a href="#">Technology</a>
                </li>
                <li>
                  <a href="#">Entertainment</a>
                </li>
                <li>
                  <a href="#">Politics</a>
                </li>
              </ul>
            </div>
          </div>
          <div class="col-lg-3 col-md-6">
            <div class="single-footer-widget">
              <h2>Subscribe</h2>
              <div class="widget-subscribe-content">
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed
                  do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                </p>
                <form class="newsletter-form">
                  <input
                    type="email"
                    class="input-newsletter"
                    placeholder="Enter your email"
                    name="EMAIL"
                    required
                  />
                  <button type="submit">Subscribe</button>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
	
    <div class="copyright-area">
      <div class="container">
        <div class="copyright-area-content">
          <p>
            Copyright © <?= date("Y") ?> JooMedia. All Rights Reserved | Developed with 
			<i class='bx bx-heart' style='color:#ff0401'></i> by 
			<a href="https://khaleb.dev" target="_blank">khaleb.dev</a>
          </p>
        </div>
      </div>
    </div>

		<div class="go-top">
			<i class="bx bx-up-arrow-alt"></i>
		</div>

		<?= $this->headScript()
			->offsetSetFile(120, $this->basePath('blog_assets/js/main.js'))
			->offsetSetFile(110, $this->basePath('blog_assets/js/wow.min.js'))
			->offsetSetFile(100, $this->basePath('blog_assets/js/contact-form-script.js'))
			->offsetSetFile(90, $this->basePath('blog_assets/js/form-validator.min.js'))
			->offsetSetFile(80, $this->basePath('blog_assets/js/jquery.ajaxchimp.min.js'))
			->offsetSetFile(70, $this->basePath('blog_assets/js/nice-select.min.js'))
			->offsetSetFile(60, $this->basePath('blog_assets/js/jquery.magnific-popup.min.js'))
			->offsetSetFile(50, $this->basePath('blog_assets/js/owl.carousel.min.js'))
			->offsetSetFile(40, $this->basePath('blog_assets/js/jquery.meanmenu.js'))
			->offsetSetFile(30, $this->basePath('blog_assets/js/bootstrap.min.js'))
			->offsetSetFile(20, $this->basePath('blog_assets/js/popper.min.js'))
			->offsetSetFile(10, $this->basePath('blog_assets/js/jquery.min.js'));
		?>
        <?= $this->inlineScript() ?>
    </body>
</html>
