<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<?= $this->doctype() ?>
<html lang="en">
    <head>
    	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<?= $this->headTitle('Sikha')->setSeparator(' :: ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
            ->appendName('keywords', '')
	        ->appendName('description', '')
	        ->appendName('language', 'English')
	        ->appendName('author', 'Khaleb Great')
        ?>

        <?php
            echo $this->headLink(['rel' => 'shortcut icon', 'href' => $this->basePath() . 'assets/media/logos/favicon.ico'])
            ->offsetSetStylesheet(20, $this->basePath('blog_assets/css/blog.fonts.css'), '')
            ->offsetSetStylesheet(10, $this->basePath('blog_assets/css/blog.style.bundle.css'), '');
        ?>
	</head>
    <body data-aos-easing="slide" data-aos-duration="800" data-aos-delay="0">
		<div class="site-wrap">
			<div class="site-mobile-menu">
				<div class="site-mobile-menu-header">
					<div class="site-mobile-menu-close mt-3">
						<span class="icon-close2 js-menu-toggle"></span>
					</div>
				</div>
				<div class="site-mobile-menu-body">
					<ul class="site-nav-wrap">
						<li>
							<a href="/category.html">Home</a>
						</li>
						<li>
							<a href="/category.html">Politics</a>
						</li>
						<li>
							<a href="/category.html">Tech</a>
						</li>
						<li>
							<a href="/category.html">Entertainment</a>
						</li>
						<li>
							<a href="/category.html">Travel</a>
						</li>
						<li>
							<a href="/category.html">Sports</a>
						</li>
						<li class="d-none d-lg-inline-block">
							<a href="/#" class="js-search-toggle"><span class="icon-search"></span></a>
						</li>
					</ul>
				</div>
			</div>
			<header class="site-navbar" role="banner">
				<div class="container-fluid">
					<div class="row align-items-center">
						<div class="col-12 search-form-wrap js-search-form">
							<form action="/#">
								<input type="text" id="s" class="form-control" placeholder="Search..." />
								<button class="search-btn" type="submit"><span class="icon-search"></span></button>
							</form>
						</div>
						<div class="col-4 site-logo">
							<a href="/index.html" class="text-black h2 mb-0">JooMedia</a>
						</div>
						<div class="col-8 text-right">
							<nav class="site-navigation" role="navigation">
								<ul class="site-menu <!--js-clone-nav--> mr-auto d-none d-lg-block mb-0">
									<li>
									<a href="/category.html">Home</a>
									</li>
									<li>
									<a href="/category.html">Politics</a>
									</li>
									<li>
									<a href="/category.html">Tech</a>
									</li>
									<li>
									<a href="/category.html">Entertainment</a>
									</li>
									<li>
									<a href="/category.html">Travel</a>
									</li>
									<li>
									<a href="/category.html">Sports</a>
									</li>
									<li class="d-none d-lg-inline-block">
									<a href="/#" class="js-search-toggle"><span
										class="icon-search"></span></a>
									</li>
								</ul>
							</nav>
							<a href="/#" class="site-menu-toggle js-menu-toggle text-black d-inline-block d-lg-none"><span class="icon-menu h3"></span></a>
						</div>
					</div>
				</div>
			</header>

			<?= $this->content ?>
			
			<div class="site-footer">
				<div class="container">
					<div class="row mb-5">
						<div class="col-md-4">
							<h3 class="footer-heading mb-4">About Us</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.
							Placeat reprehenderit magnam deleniti quasi saepe, consequatur
							atque sequi delectus dolore veritatis obcaecati quae, repellat
							eveniet omnis, voluptatem in. Soluta, eligendi, architecto.</p>
						</div>
						<div class="col-md-3 ml-auto">
							<ul class="list-unstyled float-left mr-5">
								<li>
									<a href="/#">About Us</a>
								</li>
								<li>
									<a href="/#">Advertise</a>
								</li>
								<li>
									<a href="/#">Careers</a>
								</li>
								<li>
									<a href="/#">Subscribes</a>
								</li>
								</ul>
								<ul class="list-unstyled float-left">
								<li>
									<a href="/#">Travel</a>
								</li>
								<li>
									<a href="/#">Lifestyle</a>
								</li>
								<li>
									<a href="/#">Sports</a>
								</li>
								<li>
									<a href="/#">Nature</a>
								</li>
							</ul>
						</div>
						<div class="col-md-4">
							<div>
								<h3 class="footer-heading mb-4">Connect With Us</h3>
								<p>
									<a href="/#"><span class="icon-facebook pt-2 pr-2 pb-2 pl-0"></span></a>
									<a href="/#"><span class="icon-twitter p-2"></span></a>
									<a href="/#"><span class="icon-instagram p-2"></span></a>
									<a href="/#"><span class="icon-rss p-2"></span></a>
									<a href="/#"><span class="icon-envelope p-2"></span></a>
								</p>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-12 text-center">
							<p>Copyright © <?= date("Y") ?> - All rights reserved | Made with
							<i class="icon-heart text-danger" aria-hidden="true"></i> by
							<a href="https://khaleb.dev" target="_blank">khaleb.dev</a>
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>

		<?= $this->headScript()
			->offsetSetFile(120, $this->basePath('blog_assets/js/main.js'))
			->offsetSetFile(110, $this->basePath('blog_assets/js/aos-2.3.4.js'))
			->offsetSetFile(100, $this->basePath('blog_assets/js/bootstrap-datepicker-1.6.4.min.js'))
			->offsetSetFile(90, $this->basePath('blog_assets/js/jquery.magnific-popup-1.1.0.min.js'))
			->offsetSetFile(80, $this->basePath('blog_assets/js/jquery.countdown-2.2.0.min.js'))
			->offsetSetFile(70, $this->basePath('blog_assets/js/jquery.stellar-0.6.2.min.js'))
			->offsetSetFile(60, $this->basePath('blog_assets/js/owl.carousel-2.2.1.min.js'))
			->offsetSetFile(50, $this->basePath('blog_assets/js/bootstrap.min.js'))
			->offsetSetFile(40, $this->basePath('blog_assets/js/popper-2.9.2.min.js'))
			->offsetSetFile(30, $this->basePath('blog_assets/js/jquery-ui-1.12.1.js'))
			->offsetSetFile(20, $this->basePath('blog_assets/js/jquery-migrate-3.0.1.min.js'))
			->offsetSetFile(10, $this->basePath('blog_assets/js/jquery-3.3.1.min.js'));
		?>
        <?= $this->inlineScript() ?>
    </body>
</html>
