<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->headTitle('Home');

?>

<section class="main-news-slider-area">
    <div class="container-fluid">
        <div class="main-news-slides owl-carousel owl-theme">
            <div class="news-slider-item">
                <a href="#">
                    <img src="blog_assets/imgs/main-news-slider/main-news-slider-1.jpg" alt="image" />
                </a>
                <div class="slider-content">
                    <div class="tag">Beauty</div>
                    <h3>
                        <a href="#">Perceptions of beauty and happiness from various cultures</a>
                    </h3>
                    <span><a href="#">Walters</a> / 28 September, 2021</span>
                </div>
            </div>
            <div class="news-slider-item">
                <a href="#">
                    <img src="blog_assets/imgs/main-news-slider/main-news-slider-2.jpg" alt="image" />
                </a>
                <div class="slider-content">
                    <div class="tag">Fashion</div>
                    <h3>
                        <a href="#">Beauty tips for a fresh look the day after a night out</a>
                    </h3>
                    <span><a href="#">Walters</a> / 28 September, 2021</span>
                </div>
            </div>
            <div class="news-slider-item">
                <a href="#">
                    <img src="blog_assets/imgs/main-news-slider/main-news-slider-3.jpg" alt="image" />
                </a>
                <div class="slider-content">
                    <div class="tag">Culture</div>
                    <h3>
                        <a href="#">Borderline creepy things every girl does when she has a crush</a>
                    </h3>
                    <span><a href="#">Walters</a> / 28 September, 2021</span>
                </div>
            </div>
            <div class="news-slider-item">
                <a href="#">
                    <img src="blog_assets/imgs/main-news-slider/main-news-slider-4.jpg" alt="image" />
                </a>
                <div class="slider-content">
                    <div class="tag">Lifestyle</div>
                    <h3>
                        <a href="#">Amanda Monique, combining comfort and Australian style</a>
                    </h3>
                    <span><a href="#">Walters</a> / 28 September, 2021</span>
                </div>
            </div>
            <div class="news-slider-item">
                <a href="#">
                    <img src="blog_assets/imgs/main-news-slider/main-news-slider-5.jpg" alt="image"></noscript>
                </a>
                <div class="slider-content">
                    <div class="tag">World news</div>
                    <h3>
                        <a href="#">Usability testing tools for optimizing your site in 2025</a>
                    </h3>
                    <span><a href="#">Walters</a> / 28 September, 2021</span>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="default-news-area">
    <div class="container">
        <div class="most-popular-news">
            <div class="section-title">
                <h2>Most popular</h2>
            </div>
            <div class="row">
                <div class="col-lg-4 col-md-6">
                    <div class="single-most-popular-news">
                        <div class="popular-news-image">
                            <a href="#">
                                <img src="blog_assets/imgs/most-popular/most-popular-1.jpg" alt="image" />
                            </a>
                        </div>
                        <div class="popular-news-content">
                            <span>Politics</span>
                            <h3>
                                <a href="#">The Prime Minister’s said that selfish nations are constantly dying for
                                    their won interests.</a>
                            </h3>
                            <p><a href="#">Patricia</a> / 28 September, 2021</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="single-most-popular-news">
                        <div class="popular-news-image">
                            <a href="#">
                                <img src="blog_assets/imgs/most-popular/most-popular-2.jpg" alt="image" />
                            </a>
                        </div>
                        <div class="popular-news-content">
                            <span>News</span>
                            <h3>
                                <a href="#">Manchester United’s dream of winning by a goal was fulfilled</a>
                            </h3>
                            <p><a href="#">Gonzalez</a> / 28 September, 2021</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6">
                    <div class="single-most-popular-news">
                        <div class="popular-news-image">
                            <a href="#">
                                <img src="blog_assets/imgs/most-popular/most-popular-7.jpg" alt="image"></noscript>
                            </a>
                        </div>
                        <div class="popular-news-content">
                            <span>Premer league</span>
                            <h3>
                                <a href="#">Organizing conference among our selves to make it better financially</a>
                            </h3>
                            <p><a href="#">Gonzalez</a> / 28 September, 2021</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- ads banner -->
        <div class="health-news">
            <div class="row">
                <div class="col-lg-12 col-md-12">
                    <div class="single-health-news">
                        <div class="health-news-image">
                            <a href="#">
                                <img src="assets/img/health-news/health-news-3.jpg" alt="ads ------ banner" />
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="health-news mt-5">
            <div class="row">
                <div class="col-lg-8">
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-4 col-sm-4">
                                        <div class="health-news-image">
                                            <a href="#">
                                                <img src="blog_assets/imgs/health-news/health-news-5.jpg" alt="image" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-sm-8">
                                        <div class="health-news-content">
                                            <span>News</span>
                                            <h3>
                                                <a href="#">On the advice of the doctor, Dr. Katherine Chavez
                                                    forbids taking the whole medicine</a>
                                            </h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                            <b>28 September, 2021</b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-4 col-sm-4">
                                        <div class="health-news-image">
                                            <a href="#">
                                                <img src="blog_assets/imgs/health-news/health-news-6.jpg" alt="image" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-sm-8">
                                        <div class="health-news-content">
                                            <span>Fitness</span>
                                            <h3>
                                                <a href="#">At present, diseases have become the main obstacle for
                                                    children to get out healthy</a>
                                            </h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                            <b>28 September, 2021</b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-4 col-sm-4">
                                        <div class="health-news-image">
                                            <a href="#">
                                                <img src="blog_assets/imgs/health-news/health-news-5.jpg" alt="image" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-sm-8">
                                        <div class="health-news-content">
                                            <span>News</span>
                                            <h3>
                                                <a href="#">On the advice of the doctor, Dr. Katherine Chavez
                                                    forbids taking the whole medicine</a>
                                            </h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                            <b>28 September, 2021</b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Ads -->
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-12 col-sm-12">
                                        <div class="single-health-news">
                                            <div class="health-news-image">
                                                <a href="#">
                                                    <img src="assets/img/health-news/health-news-6.jpg" alt="ads ------ banner" />
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-4 col-sm-4">
                                        <div class="health-news-image">
                                            <a href="#">
                                                <img src="blog_assets/imgs/health-news/health-news-6.jpg" alt="image" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-sm-8">
                                        <div class="health-news-content">
                                            <span>Fitness</span>
                                            <h3>
                                                <a href="#">At present, diseases have become the main obstacle for
                                                    children to get out healthy</a>
                                            </h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                            <b>28 September, 2021</b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-4 col-sm-4">
                                        <div class="health-news-image">
                                            <a href="#">
                                                <img src="blog_assets/imgs/health-news/health-news-6.jpg" alt="image" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-sm-8">
                                        <div class="health-news-content">
                                            <span>Fitness</span>
                                            <h3>
                                                <a href="#">At present, diseases have become the main obstacle for
                                                    children to get out healthy</a>
                                            </h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                            <b>28 September, 2021</b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-4 col-sm-4">
                                        <div class="health-news-image">
                                            <a href="#">
                                                <img src="blog_assets/imgs/health-news/health-news-6.jpg" alt="image" />
                                            </a>
                                        </div>
                                    </div>
                                    <div class="col-lg-8 col-sm-8">
                                        <div class="health-news-content">
                                            <span>Fitness</span>
                                            <h3>
                                                <a href="#">At present, diseases have become the main obstacle for
                                                    children to get out healthy</a>
                                            </h3>
                                            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                                                eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>
                                            <b>28 September, 2021</b>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- Ads -->
                            <div class="health-news-post">
                                <div class="row align-items-center">
                                    <div class="col-lg-12 col-sm-12">
                                        <div class="single-health-news">
                                            <div class="health-news-image">
                                                <a href="#">
                                                    <img src="assets/img/health-news/health-news-6.jpg" alt="ads ------ banner" />
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <aside class="widget-area">
                        <section class="widget widget_stay_connected">
                            <h3 class="widget-title">Stay connected</h3>
                            <ul class="stay-connected-list">
                                <li>
                                    <a href="#">
                                        <i class='bx bxl-facebook'></i>
                                        120,345 Fans
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="twitter">
                                        <i class='bx bxl-twitter'></i>
                                        25,321 Followers
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="linkedin">
                                        <i class='bx bxl-linkedin'></i>
                                        7,519 Connect
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="youtube">
                                        <i class='bx bxl-youtube'></i>
                                        101,545 Subscribers
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="instagram">
                                        <i class='bx bxl-instagram'></i>
                                        10,129 Followers
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="wifi">
                                        <i class='bx bx-wifi'></i>
                                        952 Subscribers
                                    </a>
                                </li>
                            </ul>
                        </section>
                        <section class="widget widget_most_shared">
                            <h3 class="widget-title">Sponsored Ad</h3>
                            <div class="single-most-shared">
                                <div class="most-shared-image">
                                    <a href="#">
                                        <img src="blog_assets/imgs/most-shared/most-shared-2.jpg" alt="image" />
                                    </a>
                                    <div class="most-shared-content">
                                        <h3>
                                            <a href="#">All the highlights from western fashion week summer 2021</a>
                                        </h3>
                                        <p><a href="#">Patricia</a> / 28 September, 2021</p>
                                    </div>
                                </div>
                            </div>
                        </section>
                        <section class="widget widget_latest_news_thumb">
                            <h3 class="widget-title">Latest news</h3>
                            <article class="item">
                                <a href="#" class="thumb">
                                    <span class="fullimage cover" style="background-image: url(../blog_assets/imgs/latest-news/latest-news-1.jpg);" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall">
                                        <a href="#">Negotiations on a peace agreement between the two countries</a>
                                    </h4>
                                    <span>28 September, 2021</span>
                                </div>
                            </article>
                            <article class="item">
                                <a href="#" class="thumb">
                                    <span class="fullimage cover" style="background-image: url(../blog_assets/imgs/latest-news/latest-news-2.jpg);" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall">
                                        <a href="#">Love songs helped me through heartbreak</a>
                                    </h4>
                                    <span>28 September, 2021</span>
                                </div>
                            </article>
                            <article class="item">
                                <a href="#" class="thumb">
                                    <span class="fullimage cover" style="background-image: url(../blog_assets/imgs/latest-news/latest-news-3.jpg);" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall"><a href="#">This movement aims to establish women
                                            rights</a></h4>
                                    <span>28 September, 2021</span>
                                </div>
                            </article>
                            <article class="item">
                                <a href="#" class="thumb">
                                    <span class="fullimage cover" style="background-image: url(../blog_assets/imgs/latest-news/latest-news-4.jpg);" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall"><a href="#">For the last time, he addressed the people</a></h4>
                                    <span>28 September, 2021</span>
                                </div>
                            </article>
                            <article class="item">
                                <a href="#" class="thumb">
                                    <span class="fullimage cover" style="background-image: url(../blog_assets/imgs/latest-news/latest-news-4.jpg);" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall"><a href="#">For the last time, he addressed the people</a></h4>
                                    <span>28 September, 2021</span>
                                </div>
                            </article>
                            <article class="item">
                                <a href="#" class="thumb">
                                    <span class="fullimage cover" style="background-image: url(../blog_assets/imgs/latest-news/latest-news-4.jpg);" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall"><a href="#">For the last time, he addressed the people</a></h4>
                                    <span>28 September, 2021</span>
                                </div>
                            </article>
                            <article class="item">
                                <a href="#" class="thumb">
                                    <span class="fullimage cover" style="background-image: url(../blog_assets/imgs/latest-news/latest-news-4.jpg);" role="img"></span>
                                </a>
                                <div class="info">
                                    <h4 class="title usmall"><a href="#">For the last time, he addressed the people</a></h4>
                                    <span>28 September, 2021</span>
                                </div>
                            </article>
                        </section>
                        <section class="widget widget_tag_cloud">
                            <h3 class="widget-title">Tags</h3>
                            <div class="tagcloud">
                                <a href="#">News</a>
                                <a href="#">Business</a>
                                <a href="#">Health</a>
                                <a href="#">Politics</a>
                                <a href="#">Magazine</a>
                                <a href="#">Sport</a>
                                <a href="#">Tech</a>
                                <a href="#">Video</a>
                                <a href="#">Global</a>
                                <a href="#">Culture</a>
                                <a href="#">Fashion</a>
                            </div>
                        </section>
                    </aside>
                </div>
            </div>
        </div>
    </div>
</section>