<?php

namespace Application\Entity\Repository;

use Application\Entity\Post;
use Application\Entity\PostTags;
use Application\Entity\Tags;

/**
 * PostTagsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostTagsRepository extends \Doctrine\ORM\EntityRepository
{
    public function countPostByTag(Tags $tag, $countOnlyPublished=false)
    {
        $conn = $this->getEntityManager()->getConnection();

        return $this->createQueryBuilder('tp')
            ->select('COUNT(tp.id) as totalPost')
            ->setParameter('tag', $tag->getId())
            ->join(Post::class, 'p', 'WITH', 'tp.post = p.id')
            ->where($countOnlyPublished ? 'tp.tag = :tag AND p.isDeleted = 0 AND p.isPublished = 1' : 'tp.tag = :tag AND p.isDeleted = 0')
            ->getQuery()
            ->getOneOrNullResult();
    }


    // public function fetchCountPostByTag()
    // {
    //     $conn = $this->getEntityManager()->getConnection();

    //     return $this->createQueryBuilder('tp')
    //         ->andWhere('tp.tag = :tag', 'tp.paymentStatus = :paymentStatus', 'tp.memberTypeId = :memberTypeId')
    //         ->setParameter('tag', $tag)
    //         ->select('COUNT(tp.id) as totalPost')
    //         ->getQuery()
    //         ->getOneOrNullResult();
    // }
}
