<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->headTitle('Groups');

// $this->headLink()
//     ->offsetSetStylesheet(10, $this->basePath('assets/css/pages/login/classic/login-5.css'));
?>

<div class="row">
    <?php
        if (empty($groups)) :
    ?>
    <div class="col-12">
        <div class="card card-custom card-stretch gutter-b">
            <div class="card-body d-flex flex-column p-0">
                <div class="d-flex align-items-center justify-content-between card-spacer">
                    <div class="d-flex flex-column mr-2">
                        <i><span class="text-muted font-weight-bold mt-2">No group(s)</span></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
        else :
            foreach ($groups as $group) :
                $postCount = count($entityPost->findBy(['group' => $group, 'isDeleted' => false, 'isPublished' => true]));
    ?>
    <div class="col-xl-4">
        <div class="card card-custom card-stretch gutter-b">
            <div class="card-body d-flex flex-column p-0">
                <div class="d-flex align-items-center justify-content-between card-spacer">
                    <div class="d-flex flex-column mr-2">
                        <a href="<?= $this->url('app/manage-groups', ['id' => $group->getId()]) ?>" class="text-dark-75 text-hover-warning font-weight-bolder font-size-h5"><?= $group->getName() ?></a>
                        <span class="text-muted font-weight-bold mt-2"><?= $group->getDescription() ?></span>
                    </div>
                    <span class="symbol symbol-light-success symbol-45">
                        <span class="symbol-label font-weight-bolder font-size-h6"><?= $postCount ?></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <?php
            endforeach;
        endif;
    ?>
</div>

<?php
    // $this->headScript()
    //     ->offsetSetFile(41, $this->basePath('assets/js/pages/custom/login/login-general.js'));

    $this->inlineScript()->captureStart();
?>

<?php
    $this->inlineScript()->captureEnd();
?>