<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->headTitle('Groups');
$this->backOfficeMenu()->setActiveItemId('groups');

?>
<div class="row">
    <div class="col-12 text-right">
        <span class="btn btn-primary mb-3 text-hover-primary" data-toggle="modal" data-target="#createGroupModal">+</span>
    </div>
</div>
<div class="row">
    <?php
        if (empty($groups)) :
    ?>
    <div class="col-12">
        <div class="card card-custom card-stretch gutter-b">
            <div class="card-body d-flex flex-column p-0">
                <div class="d-flex align-items-center justify-content-between card-spacer">
                    <div class="d-flex flex-column mr-2">
                        <i><span class="text-muted font-weight-bold mt-2">No group(s)</span></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
        else :
            foreach ($groups as $group) :
                $postCount = count($entityPost->findBy(['group' => $group, 'isDeleted' => false]));
    ?>
    <div class="col-xl-4">
        <div class="card card-custom card-stretch gutter-b">
            <div class="card-body d-flex flex-column p-0">
                <div class="d-flex align-items-center justify-content-between card-spacer">
                    <div class="d-flex flex-column mr-2">
                        <a href="<?= $this->url('app/manage-groups', ['id' => $group->getId()]) ?>" class="text-dark-75 text-hover-warning font-weight-bolder font-size-h5"><?= $group->getName() ?></a>
                        <span class="text-muted font-weight-bold mt-2"><?= $group->getDescription() ?></span>
                    </div>
                    <span class="symbol symbol-light-success symbol-45">
                        <span class="symbol-label font-weight-bolder font-size-h6"><?= $postCount ?></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <?php
            endforeach;
        endif;
    ?>
</div>

<div class="modal fade" id="createGroupModal" tabindex="-1" role="dialog" aria-labelledby="createGroupModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createGroupModalLabel">Create Group</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i aria-hidden="true" class="ki ki-close"></i>
        </button>
      </div>
      <form>
        <div class="modal-body">
          <div data-scroll="true" data-height="220">
            <div class="form-group">
              <label for="txtGroupName">Name<span class="text-danger">*</span></label>
              <input type="text" name="txtGroupName" id="txtGroupName" class="form-control" placeholder="Enter group name" value="">
              <span class="form-text text-muted">This name is visible to viewers on your website.</span>
            </div>
            <div class="form-group">
              <label for="txtGroupDexcription">Tag Description</label>
              <textarea name="txtGroupDexcription" class="form-control" id="txtGroupDexcription" rows="3"></textarea>
            </div>
            <!-- <div class="form-group mb-1">
                <input type="checkbox" name="makeDefault" id="makeDefault" value="1">
                <label for="makeDefault">Make Default</label>
            </div> -->
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary font-weight-bold" id="btnCreateGroup">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>

<?php
    $this->inlineScript()->captureStart();
?>
$(document).ready(function(){
  $(document).on('click', '#btnCreateGroup', function(){
    $(this).text('Create ');
    $(this).addClass("spinner spinner-right spinner-white");
    $(this).attr('disabled', 'disabled');
    let btn = $(this);
    $.ajax({
      url: "<?=$utility::API_DOMAIN?>/v1/group",
      type: "POST",
      //dataType: 'json',
      //headers: {
      //  "Authorization": "Bearer 'Token'"
      //},
      data: {
        name: $('#txtGroupName').val(),
        description: $('#txtGroupDexcription').val(),
        default: 'false'
      },
      success: function(response){
        btn.removeClass("spinner spinner-right spinner-white");
        if (response.code == 201) {
            setTimeout(function() {
                window.location.assign('<?= $this->url('app/manage-groups')?>');
            }, 1000);
        }
        else {

        }
        setTimeout(function() {
          btn.removeAttr('disabled');
          btn.html('Create');
        }, 1000);
      }
    });

  });
});
<?php
    $this->inlineScript()->captureEnd();
?>