<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */

$this->headTitle('Tags');
$this->backOfficeMenu()->setActiveItemId('tags');

// $this->headLink()
//     ->offsetSetStylesheet(10, $this->basePath('assets/css/pages/login/classic/login-5.css'));
?>
<div class="row">
    <div class="col-12 text-right">
        <span class="btn btn-primary mb-3 text-hover-primary" data-toggle="modal" data-target="#createTagModal">+</span>
    </div>
</div>
<div class="row">
    <?php
        if (empty($tags)) :
    ?>
    <div class="col-12">
        <div class="card card-custom card-stretch gutter-b">
            <div class="card-body d-flex flex-column p-0">
                <div class="d-flex align-items-center justify-content-between card-spacer">
                    <div class="d-flex flex-column mr-2">
                        <i><span class="text-muted font-weight-bold mt-2">No tag(s)</span></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <?php
        else :
            foreach ($tags as $tag) :
                $postCount = $postCounter->countPostByTag($tag, false);
    ?>
    <div class="col-xl-4">
        <div class="card card-custom card-stretch gutter-b">
            <div class="card-body d-flex flex-column p-0">
                <div class="d-flex align-items-center justify-content-between card-spacer">
                    <div class="d-flex flex-column mr-2">
                        <a href="<?= $this->url('app/manage-tags', ['id' => $tag->getId()]) ?>" class="text-dark-75 text-hover-warning font-weight-bolder font-size-h5"><?= $tag->getName() ?></a>
                        <span class="text-muted font-weight-bold mt-2"><?= $tag->getDescription() ?></span>
                    </div>
                    <span class="symbol symbol-light-warning symbol-45">
                        <span class="symbol-label font-weight-bolder font-size-h6"><?= $postCount['totalPost'] ?></span>
                    </span>
                </div>
            </div>
        </div>
    </div>
    <?php
            endforeach;
        endif;
    ?>
</div>

<div class="modal fade" id="createTagModal" tabindex="-1" role="dialog" aria-labelledby="createTagModal" aria-hidden="true">
  <div class="modal-dialog modal-dialog-scrollable" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="createTagModalLabel">Create Tag</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <i aria-hidden="true" class="ki ki-close"></i>
        </button>
      </div>
      <form>
        <div class="modal-body">
          <div data-scroll="true" data-height="220">
            <div class="form-group">
              <label for="txtTagName">Name<span class="text-danger">*</span></label>
              <input type="text" name="txtTagName" id="txtTagName" class="form-control" placeholder="Enter tag name" value="">
              <span class="form-text text-muted">This name is visible to viewers on your website.</span>
            </div>
            <div class="form-group">
              <label for="txtTagDexcription">Tag Description</label>
              <textarea name="txtTagDexcription" class="form-control" id="txtTagDexcription" rows="3"></textarea>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-light-primary font-weight-bold" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary font-weight-bold" id="btnCreateTag">Create</button>
        </div>
      </form>
    </div>
  </div>
</div>

<?php
    // $this->headScript()
    //     ->offsetSetFile(41, $this->basePath('assets/js/pages/custom/login/login-general.js'));

    $this->inlineScript()->captureStart();
?>
$(document).ready(function(){
  $(document).on('click', '#btnCreateTag', function(){
    $(this).text('Create ');
    $(this).addClass("spinner spinner-right spinner-white");
    $(this).attr('disabled', 'disabled');
    let btn = $(this);
    $.ajax({
      url: "<?=$utility::API_DOMAIN?>/v1/tag",
      type: "POST",
      //dataType: 'json',
      //headers: {
      //  "Authorization": "Bearer 'Token'"
      //},
      data: {
        name: $('#txtTagName').val(),
        description: $('#txtTagDexcription').val()
      },
      success: function(response){
        btn.removeClass("spinner spinner-right spinner-white");
        if (response.code == 201) {
            setTimeout(function() {
                window.location.assign('<?= $this->url('app/manage-tags')?>');
            }, 1000);
        }
        else {

        }
        setTimeout(function() {
          btn.removeAttr('disabled');
          btn.html('Create');
        }, 1000);
      }
    });

  });
});
<?php
    $this->inlineScript()->captureEnd();
?>